-- require("haidnguyen.plugin-setup")
-- require("haidnguyen.core.colorscheme")
-- require("haidnguyen.plugins.lsp")
-- require("haidnguyen.plugins.cmp")
-- require("haidnguyen.plugins.comment")
-- require("haidnguyen.plugins.nvim-tree")
-- require("haidnguyen.plugins.lualine")
-- require("haidnguyen.plugins.telescope")
-- require("haidnguyen.plugins.treesiter")
-- require("haidnguyen.plugins.mason")
-- require("haidnguyen.plugins.lspsaga")
-- require("haidnguyen.plugins.autopairs")
-- require("haidnguyen.plugins.gitsigns")
-- require("haidnguyen.plugins.bufferline")
-- require 'haidnguyen.plugins.lsp-signature'
-- require("haidnguyen.plugins.toggleterm")
-- require("haidnguyen.plugins.catppuccin")
-- require("haidnguyen.plugins.pqf")
-- require("haidnguyen.plugins.scrollbar")
-- require("haidnguyen.plugins.which-key")
-- require("haidnguyen.plugins.typescript")
-- require("haidnguyen.plugins.conform")
-- require("haidnguyen.plugins.auto-session")

-- New lazy.nvim config
require("config.lazy")
require("haidnguyen.core.options")
require("haidnguyen.core.keymaps")
